In [1]:
import pandas as pd
df = pd.read_csv('efficiency_result_processed.csv')

In [2]:
disabled_miss_ratios = df[df['rebalance_strategy'] == 'disabled'].set_index(['trace_name', 'wsr', 'allocator'])['miss_ratio']
def get_disabled_miss_ratio(row):
    key = (row['trace_name'], row['wsr'], row['allocator'])
    return disabled_miss_ratios.get(key, None)

df['disabled_miss_ratio'] = df.apply(get_disabled_miss_ratio, axis=1)
df['miss_ratio_reduction_from_disabled_ratio'] = df['miss_ratio_reduction_from_disabled'] / df['disabled_miss_ratio']

In [7]:
df.columns

Index(['rebalanced_slabs', 'n_rebalanced_slabs', 'miss_ratio', 'throughput',
       'n_alloc_failures', 'trace_name', 'number_of_requests', 'wsr',
       'slab_size', 'slab_cnt', 'rebalance_strategy', 'allocator', 'tag',
       'monitor_interval', 'uuid', 'qps', 'wss', 'number_of_objects',
       'file_name', 'memory_requirement', 'compulsory_miss_ratio_byte',
       'max_req_size', 'max_obj_size', 'trace_file', 'time_span', 'purpose',
       'min_req_size', 'number_of_req_GiB', 'cpu_requirement', 'download_path',
       'category', 'compulsory_miss_ratio_req', 'number_of_obj_GiB',
       'num_slab_classes', 'frequency_mean', 'min_obj_size',
       'poolRebalanceIntervalSec', 'lru2qColdPct', 'thresholdMI',
       'mhMovingAverageParam', 'mhMinDiff', 'rebalanceOnRecordAccess',
       'countColdTailHitsOnly', 'rebalanceStrategy', 'rebalanceDiffRatio',
       'lruRefreshSec', 'allocFactor', 'mhOnlyUpdateHitIfRebalance',
       'minRequestsObserved', 'thresholdAI', 'minAllocSize', 'maxAllocSize',
       'lamaMinThreshold', 'cacheSizeMB', 'lru2qHotPct', 'maxDecayInterval',
       'mhMinDiffRatio', 'poolResizeIntervalSec', 'emrHigh', 'emrLow',
       'moveOnSlabRelease', 'thresholdAD', 'thresholdMD', 'enableLookaside',
       'onlySetIfMiss', 'replayGeneratorConfig', 'generator', 'numThreads',
       'zstdTrace', 'repeatTraceReplay', 'compressed', 'numOps',
       'ignoreLargeReq', 'repeatOpCount', 'timestampFactor', 'traceFileName',
       'useTraceTimer', 'prepopulateCache', 'base_dir',
       'miss_ratio_reduction_from_disabled',
       'miss_ratio_reduction_from_lru_disabled', 'tuned_improvement',
       'disabled_miss_ratio', 'miss_ratio_reduction_from_disabled_ratio'],
      dtype='object')

In [14]:
display(df[(df['trace_name'] == 'meta_202210_kv') & (df['allocator'] == 'LRU')].sort_values(by = 'miss_ratio_reduction_from_disabled_ratio', ascending=False)\
    [['wsr', 'allocator', 'rebalance_strategy', 'miss_ratio_reduction_from_disabled_ratio', 'miss_ratio_reduction_from_disabled']].head(3))

display(df[(df['trace_name'] == 'meta_202210_kv') & (df['allocator'] == 'LRU2Q')].sort_values(by = 'miss_ratio_reduction_from_disabled_ratio', ascending=False)\
    [['wsr', 'allocator', 'rebalance_strategy', 'miss_ratio_reduction_from_disabled_ratio', 'miss_ratio_reduction_from_disabled']].head(3))

display(df[(df['trace_name'] == 'meta_202210_kv') & (df['allocator'] == 'TINYLFU')].sort_values(by = 'miss_ratio_reduction_from_disabled_ratio', ascending=False)\
    [['wsr', 'allocator', 'rebalance_strategy', 'miss_ratio_reduction_from_disabled_ratio', 'miss_ratio_reduction_from_disabled']].head(3))

,wsr,allocator,rebalance_strategy,miss_ratio_reduction_from_disabled_ratio,miss_ratio_reduction_from_disabled
54,0.02,LRU,marginal-hits-tuned,0.474875,0.038649
78,0.05,LRU,marginal-hits-tuned,0.455651,0.028619
76,0.05,LRU,hits,0.449388,0.028226

,wsr,allocator,rebalance_strategy,miss_ratio_reduction_from_disabled_ratio,miss_ratio_reduction_from_disabled
62,0.020,LRU2Q,marginal-hits-tuned,0.481815,0.037087
38,0.010,LRU2Q,marginal-hits-tuned,0.449273,0.042094
14,0.005,LRU2Q,marginal-hits-tuned,0.430332,0.049640

,wsr,allocator,rebalance_strategy,miss_ratio_reduction_from_disabled_ratio,miss_ratio_reduction_from_disabled
88,0.05,TINYLFU,marginal-hits-tuned,0.454739,0.028541
94,0.05,TINYLFU,hits,0.448239,0.028133
64,0.02,TINYLFU,marginal-hits-tuned,0.447077,0.036476

In [15]:
display(df[(df['category'] == 'twitter-kv') & (df['allocator'] == 'LRU')].sort_values(by = 'miss_ratio_reduction_from_disabled_ratio', ascending=False)\
    [['wsr', 'allocator', 'rebalance_strategy', 'miss_ratio_reduction_from_disabled_ratio', 'miss_ratio_reduction_from_disabled']].head(3))

display(df[(df['category'] == 'twitter-kv') & (df['allocator'] == 'LRU2Q')].sort_values(by = 'miss_ratio_reduction_from_disabled_ratio', ascending=False)\
    [['wsr', 'allocator', 'rebalance_strategy', 'miss_ratio_reduction_from_disabled_ratio', 'miss_ratio_reduction_from_disabled']].head(3))

display(df[(df['category'] == 'twitter-kv') & (df['allocator'] == 'TINYLFU')].sort_values(by = 'miss_ratio_reduction_from_disabled_ratio', ascending=False)\
    [['wsr', 'allocator', 'rebalance_strategy', 'miss_ratio_reduction_from_disabled_ratio', 'miss_ratio_reduction_from_disabled']].head(3))

,wsr,allocator,rebalance_strategy,miss_ratio_reduction_from_disabled_ratio,miss_ratio_reduction_from_disabled
2028,0.1,LRU,tail-age,0.985254,0.201308
2029,0.1,LRU,hits,0.985113,0.201279
2026,0.1,LRU,eviction-rate,0.982887,0.200825

,wsr,allocator,rebalance_strategy,miss_ratio_reduction_from_disabled_ratio,miss_ratio_reduction_from_disabled
2039,0.1,LRU2Q,marginal-hits-tuned,0.986302,0.186407
2037,0.1,LRU2Q,hits,0.984207,0.186011
2034,0.1,LRU2Q,eviction-rate,0.981722,0.185541

,wsr,allocator,rebalance_strategy,miss_ratio_reduction_from_disabled_ratio,miss_ratio_reduction_from_disabled
2047,0.1,TINYLFU,hits,0.984613,0.188804
2046,0.1,TINYLFU,tail-age,0.983554,0.188601
2044,0.1,TINYLFU,eviction-rate,0.982003,0.188303

In [16]:
display(df[(df['category'] == 'wiki-cdn') & (df['allocator'] == 'LRU')].sort_values(by = 'miss_ratio_reduction_from_disabled_ratio', ascending=False)\
    [['wsr', 'allocator', 'rebalance_strategy', 'miss_ratio_reduction_from_disabled_ratio', 'miss_ratio_reduction_from_disabled']].head(3))

display(df[(df['category'] == 'wiki-cdn') & (df['allocator'] == 'LRU2Q')].sort_values(by = 'miss_ratio_reduction_from_disabled_ratio', ascending=False)\
    [['wsr', 'allocator', 'rebalance_strategy', 'miss_ratio_reduction_from_disabled_ratio', 'miss_ratio_reduction_from_disabled']].head(3))

display(df[(df['category'] == 'wiki-cdn') & (df['allocator'] == 'TINYLFU')].sort_values(by = 'miss_ratio_reduction_from_disabled_ratio', ascending=False)\
    [['wsr', 'allocator', 'rebalance_strategy', 'miss_ratio_reduction_from_disabled_ratio', 'miss_ratio_reduction_from_disabled']].head(3))

,wsr,allocator,rebalance_strategy,miss_ratio_reduction_from_disabled_ratio,miss_ratio_reduction_from_disabled
2492,0.01,LRU,marginal-hits-tuned,0.553278,0.144489
2486,0.01,LRU,lama,0.520074,0.135818
2540,0.01,LRU,marginal-hits-tuned,0.479365,0.170037

,wsr,allocator,rebalance_strategy,miss_ratio_reduction_from_disabled_ratio,miss_ratio_reduction_from_disabled
2500,0.01,LRU2Q,marginal-hits-tuned,0.537881,0.129726
2494,0.01,LRU2Q,lama,0.509784,0.122950
2548,0.01,LRU2Q,marginal-hits-tuned,0.465237,0.152313

,wsr,allocator,rebalance_strategy,miss_ratio_reduction_from_disabled_ratio,miss_ratio_reduction_from_disabled
2502,0.01,TINYLFU,marginal-hits-tuned,0.534550,0.120076
2504,0.01,TINYLFU,lama,0.500042,0.112324
2503,0.01,TINYLFU,marginal-hits,0.477732,0.107313

In [17]:
display(df[(df['category'] == 'meta-cdn') & (df['allocator'] == 'LRU')].sort_values(by = 'miss_ratio_reduction_from_disabled_ratio', ascending=False)\
    [['wsr', 'allocator', 'rebalance_strategy', 'miss_ratio_reduction_from_disabled_ratio', 'miss_ratio_reduction_from_disabled']].head(3))

display(df[(df['category'] == 'meta-cdn') & (df['allocator'] == 'LRU2Q')].sort_values(by = 'miss_ratio_reduction_from_disabled_ratio', ascending=False)\
    [['wsr', 'allocator', 'rebalance_strategy', 'miss_ratio_reduction_from_disabled_ratio', 'miss_ratio_reduction_from_disabled']].head(3))

display(df[(df['category'] == 'meta-cdn') & (df['allocator'] == 'TINYLFU')].sort_values(by = 'miss_ratio_reduction_from_disabled_ratio', ascending=False)\
    [['wsr', 'allocator', 'rebalance_strategy', 'miss_ratio_reduction_from_disabled_ratio', 'miss_ratio_reduction_from_disabled']].head(3))

,wsr,allocator,rebalance_strategy,miss_ratio_reduction_from_disabled_ratio,miss_ratio_reduction_from_disabled
480,0.01,LRU,lama,0.076355,0.031705
528,0.01,LRU,lama,0.074636,0.043185
504,0.01,LRU,lama,0.073225,0.050746

,wsr,allocator,rebalance_strategy,miss_ratio_reduction_from_disabled_ratio,miss_ratio_reduction_from_disabled
536,0.01,LRU2Q,lama,0.073899,0.041531
512,0.01,LRU2Q,lama,0.072351,0.048959
488,0.01,LRU2Q,lama,0.070881,0.028723

,wsr,allocator,rebalance_strategy,miss_ratio_reduction_from_disabled_ratio,miss_ratio_reduction_from_disabled
546,0.01,TINYLFU,lama,0.073882,0.042278
522,0.01,TINYLFU,lama,0.071766,0.049375
498,0.01,TINYLFU,lama,0.071538,0.029664

In [3]:
display(df[(df['trace_name'] == 'meta_202210_kv') & (df['allocator'] == 'LRU')].sort_values(by = 'miss_ratio_reduction_from_disabled_ratio', ascending=True)\
    [['wsr', 'allocator', 'rebalance_strategy', 'miss_ratio_reduction_from_disabled_ratio', 'miss_ratio_reduction_from_disabled']].head(3))

display(df[(df['trace_name'] == 'meta_202210_kv') & (df['allocator'] == 'LRU2Q')].sort_values(by = 'miss_ratio_reduction_from_disabled_ratio', ascending=True)\
    [['wsr', 'allocator', 'rebalance_strategy', 'miss_ratio_reduction_from_disabled_ratio', 'miss_ratio_reduction_from_disabled']].head(3))

display(df[(df['trace_name'] == 'meta_202210_kv') & (df['allocator'] == 'TINYLFU')].sort_values(by = 'miss_ratio_reduction_from_disabled_ratio', ascending=True)\
    [['wsr', 'allocator', 'rebalance_strategy', 'miss_ratio_reduction_from_disabled_ratio', 'miss_ratio_reduction_from_disabled']].head(3))

,wsr,allocator,rebalance_strategy,miss_ratio_reduction_from_disabled_ratio,miss_ratio_reduction_from_disabled
151,0.4,LRU,marginal-hits,-0.166260,-0.005877
123,0.2,LRU,tail-age,-0.025622,-0.001108
99,0.1,LRU,tail-age,-0.008331,-0.000442

,wsr,allocator,rebalance_strategy,miss_ratio_reduction_from_disabled_ratio,miss_ratio_reduction_from_disabled
159,0.400,LRU2Q,marginal-hits,-0.183534,-0.006385
135,0.200,LRU2Q,marginal-hits,-0.044743,-0.001851
10,0.005,LRU2Q,free-mem,0.000000,0.000000

,wsr,allocator,rebalance_strategy,miss_ratio_reduction_from_disabled_ratio,miss_ratio_reduction_from_disabled
161,0.40,TINYLFU,marginal-hits,-0.150237,-0.005316
93,0.05,TINYLFU,tail-age,-0.116807,-0.007331
117,0.10,TINYLFU,tail-age,-0.099707,-0.005262

In [4]:
display(df[(df['category'] == 'twitter-kv') & (df['allocator'] == 'LRU')].sort_values(by = 'miss_ratio_reduction_from_disabled_ratio', ascending=True)\
    [['wsr', 'allocator', 'rebalance_strategy', 'miss_ratio_reduction_from_disabled_ratio', 'miss_ratio_reduction_from_disabled']].head(3))

display(df[(df['category'] == 'twitter-kv') & (df['allocator'] == 'LRU2Q')].sort_values(by = 'miss_ratio_reduction_from_disabled_ratio', ascending=True)\
    [['wsr', 'allocator', 'rebalance_strategy', 'miss_ratio_reduction_from_disabled_ratio', 'miss_ratio_reduction_from_disabled']].head(3))

display(df[(df['category'] == 'twitter-kv') & (df['allocator'] == 'TINYLFU')].sort_values(by = 'miss_ratio_reduction_from_disabled_ratio', ascending=True)\
    [['wsr', 'allocator', 'rebalance_strategy', 'miss_ratio_reduction_from_disabled_ratio', 'miss_ratio_reduction_from_disabled']].head(3))

,wsr,allocator,rebalance_strategy,miss_ratio_reduction_from_disabled_ratio,miss_ratio_reduction_from_disabled
1867,0.1,LRU,eviction-rate,-3.183376,-0.201410
1253,0.1,LRU,eviction-rate,-1.294936,-0.061504
2463,0.1,LRU,eviction-rate,-1.120223,-0.006485

,wsr,allocator,rebalance_strategy,miss_ratio_reduction_from_disabled_ratio,miss_ratio_reduction_from_disabled
1875,0.1,LRU2Q,eviction-rate,-3.339393,-0.206538
1261,0.1,LRU2Q,eviction-rate,-1.310286,-0.058503
2471,0.1,LRU2Q,eviction-rate,-1.172123,-0.006378

,wsr,allocator,rebalance_strategy,miss_ratio_reduction_from_disabled_ratio,miss_ratio_reduction_from_disabled
1884,0.1,TINYLFU,eviction-rate,-3.534422,-0.221679
1271,0.1,TINYLFU,eviction-rate,-1.216709,-0.057944
2481,0.1,TINYLFU,eviction-rate,-1.117109,-0.006474

In [5]:
"""
slab rebalance can significantly improve cache efficiency
"""

max_reduction_by_category = df.groupby('category')['miss_ratio_reduction_from_disabled'].max().sort_values(ascending=False)
max_reduction_details = df.loc[df.groupby('category')['miss_ratio_reduction_from_disabled'].idxmax()]

print("Details of configurations achieving maximum reduction by category:")
display_cols = ['category', 'trace_name', 'wsr', 'allocator', 'rebalance_strategy', 
                'miss_ratio_reduction_from_disabled', 'miss_ratio', 'rebalanced_slabs']
max_reduction_details[display_cols].sort_values('miss_ratio_reduction_from_disabled', ascending=False)

Details of configurations achieving maximum reduction by category:

,category,trace_name,wsr,allocator,rebalance_strategy,miss_ratio_reduction_from_disabled,miss_ratio,rebalanced_slabs
2200,twitter-kv,twitter_cluster50,0.01,TINYLFU,marginal-hits,0.329998,0.280395,2792
2540,wiki-cdn,wiki_2019u,0.01,LRU,marginal-hits-tuned,0.170037,0.184676,9457
340,meta-kv,meta_memcache_2024_kv,0.01,LRU,hits,0.069548,0.127822,84
504,meta-cdn,meta_rnha,0.01,LRU,lama,0.050746,0.642264,3022